# 版本
version: "3"
# 服务
services:
  # nginx 配置
  nginx:
    build:
      context: ./services/nginx
      args: 
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
      container_name: nginx
      ports: 
        - "${NGINX_HTTP_HOST_PORT}:80"
        - "${NGINX_HTTPS_HOST_PORT}:443"
      volumes:  
        - ${SOURCE_DIR}:/www
        - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
        - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
        - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
        - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcig_params:ro
        - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      environment: 
        TZ: "$TZ"
      restart: always
      networks: 
        - default
# 网路
networks: 
  default: