# 版本
version: "3"
# 服务
services:
  # nginx 配置
  nginx:
    build:
      context: ./services/nginx
      args: 
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports: 
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:  
      - ${SOURCE_DIR}:/www
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcig_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment: 
      TZ: "$TZ"
    restart: always
    networks: 
      - default

  # php7的配置
  # php:
  #   build:
  #     context: ./services/php
  #     args:
  #       PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
  #       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
  #       PHP_EXTENSIONS: ${PHP_EXTENSIONS}
  #       TZ: "$TZ"
  #   container_name: php
  #   expose: 
  #     - 9501
  #   extra_hosts: 
  #     - "www.site1.com:172.17.0.1"
  #   volumes: 
  #     - ${SOURCE_DIR}:/www/:rw
  #     - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
  #     - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
  #     - ${PHP_LOG_DIR}:/var/log/php
  #     - ${DATA_DIR}/composer:/tmp/composer
  #   restart: always
  #   cap_add: 
  #     - SYS_PTRACE
  #   networks: 
  #     - default

  #  php56:
  build:
    context: ./services/php
    args:
      PHP_VERSION: php:${PHP56_VERSION}-fpm-alpine
      CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
      PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
      TZ: "$TZ"
    container_name: php56
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP56_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  # php54:
  # build:
  #   context: ./services/php54
  #   args:
  #     PHP_VERSION: php:${PHP54_VERSION}-fpm
  #     CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
  #     PHP_EXTENSIONS: ${PHP54_EXTENSIONS}
  #     TZ: "$TZ"
  #   container_name: php54
  #   volumes:
  #     - ${SOURCE_DIR}:/www/:rw
  #     - ${PHP54_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
  #     - ${PHP54_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
  #     - ${PHP54_LOG_DIR}:/var/log/php
  #     - ${DATA_DIR}/composer:/tmp/composer
  #   restart: always
  #   cap_add:
  #     - SYS_PTRACE
  #   networks:
  #     - default

# 网路
networks: 
  default: